apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
  labels:
    app: counter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
        - name: counter-app
          image: nithinmys/click_counter_docker:thirdtrigger
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: counter-app-service
spec:
  selector:
    app: counter-app
  ports:
    - protocol: TCP
      port: 8081         # service port
      targetPort: 8081   # must match containerPort
  type: NodePort         # change to LoadBalancer on cloud
